baseURL = 'https://salva989.github.io/blog-di-salva/'
languageCode = 'en-us'
title = 'blog di Salva'
theme = 'PaperMod'

[params]
  # Basic configuration
  env = "production"
  description = "Un blog moderno e veloce con Hugo e PaperMod"
  author = "Salva989"
  
  # Theme-specific settings
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.profileMode]
  enabled = true 
  title = "Ciaooo 👋"
  subtitle = "Benvenuto forestiero!"
  imageUrl = "https://avatars.githubusercontent.com/u/179056148?v=4"
  imageWidth = 120
  imageHeight = 120

[params.homeInfoParams]
  Title = "Ciaoo 👋"
  Content = "Benvenuto forestiero!"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Salva989/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
