baseURL = 'https://salva989.github.io/blog-facile/'
languageCode = 'en-us'
title = 'Blog Facile'
theme = 'PaperMod'

[params]
  # Basic configuration
  env = "production"
  description = "Un blog moderno e veloce con Hugo e PaperMod"
  author = "Salva989"
  
  # Theme-specific settings
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.homeInfoParams]
  Title = "Welcome to My Blog"
  Content = "Welcome to my blog built with Hugo and PaperMod theme!"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
